/**
 * Insert Employee Profile for DEBAJYOTI SARKAR
 * User: sarkardebajyoti@gmail.com
 * User._id: 69ca17378fc10e37292f18ce
 * Role: teacher
 * 
 * Department: Academic Department (697086a2abb4820c05aeca50)
 * Designation: Teacher Foundation (699eff156a6ae8d6fa71946a)
 *   (alternatively Teacher All India: 699efeff6a6ae8d6fa71909c)
 */

import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Employee from '../models/HR/Employee.js';
import User from '../models/User.js';

dotenv.config();

async function insertEmployee() {
    try {
        await mongoose.connect(process.env.MONGO_URL);
        console.log('Connected to MongoDB');

        const email = 'sarkardebajyoti@gmail.com';
        const userId = '69ca17378fc10e37292f18ce';

        // Safety check: make sure user exists
        const user = await User.findById(userId);
        if (!user) {
            console.error('User not found! Aborting.');
            process.exit(1);
        }
        console.log('Found user:', user.name, user.email, user.role);

        // Safety check: make sure employee doesn't already exist
        const existingEmployee = await Employee.findOne({
            $or: [{ email }, { user: userId }]
        });
        if (existingEmployee) {
            console.log('Employee already exists:', existingEmployee.employeeId, existingEmployee.name);
            console.log('No action taken.');
            await mongoose.disconnect();
            return;
        }

        // Create employee profile
        const newEmployee = new Employee({
            user: new mongoose.Types.ObjectId(userId),
            name: 'DEBAJYOTI SARKAR',
            email: email,
            department: new mongoose.Types.ObjectId('697086a2abb4820c05aeca50'),  // Academic Department
            designation: new mongoose.Types.ObjectId('699eff156a6ae8d6fa71946a'), // Teacher Foundation
            typeOfEmployment: 'Full Time',
            status: 'Active',
            // employeeId is auto-generated by the model's pre-validate hook
        });

        const saved = await newEmployee.save();
        console.log('\n✅ Employee profile created successfully!');
        console.log('Employee ID:', saved.employeeId);
        console.log('Name:', saved.name);
        console.log('Email:', saved.email);
        console.log('_id:', saved._id);
        console.log('Department:', saved.department);
        console.log('Designation:', saved.designation);
        console.log('Status:', saved.status);

        await mongoose.disconnect();
    } catch (error) {
        console.error('Error:', error.message);
        if (error.errors) {
            console.error('Validation errors:', JSON.stringify(error.errors, null, 2));
        }
    }
}

insertEmployee();
